/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fuzzysatisfaction;

import java.awt.Color;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import static java.lang.Math.abs;
import java.util.Scanner;
import javax.swing.JFileChooser;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author ratih
 */
public class fuzzyChart extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public fuzzyChart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnFuzzy = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRelaxTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCBFuzzyType = new javax.swing.JComboBox<>();
        jSimulationBtn = new javax.swing.JButton();
        jBtnHelp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jIdealTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFileTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnFuzzy.setText("Fuzzy Representation");
        jBtnFuzzy.setEnabled(false);
        jBtnFuzzy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFuzzyActionPerformed(evt);
            }
        });

        jButton2.setText("Open Excel File");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Fuzzy Representation Creator");

        jLabel2.setText("Relax variable :");

        jRelaxTxt.setText("0");

        jLabel3.setText("Fuzzy type :");

        jCBFuzzyType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "One Side", "Two Side" }));
        jCBFuzzyType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBFuzzyTypeActionPerformed(evt);
            }
        });

        jSimulationBtn.setText("Simulation Data");
        jSimulationBtn.setEnabled(false);
        jSimulationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSimulationBtnActionPerformed(evt);
            }
        });

        jBtnHelp.setText("Help");
        jBtnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHelpActionPerformed(evt);
            }
        });

        jLabel4.setText("Ideal:");

        jIdealTxt.setEnabled(false);

        jLabel5.setText("File :");

        jFileTxt.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214)
                        .addComponent(jBtnHelp))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFileTxt))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jSimulationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtnFuzzy))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRelaxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jCBFuzzyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(49, 49, 49)
                                            .addComponent(jLabel4)))
                                    .addGap(15, 15, 15)
                                    .addComponent(jIdealTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnHelp)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jFileTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBFuzzyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jIdealTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jRelaxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnFuzzy)
                    .addComponent(jSimulationBtn))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String myFile;
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File(System.getProperty("user.dir")));
        int result = fc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fc.getSelectedFile();
            myFile = selectedFile.getAbsolutePath().replaceAll("\\\\", "/");
            //System.out.println("Selected file: " + myFile);
        }
        jSimulationBtn.setEnabled(true);
        jBtnFuzzy.setEnabled(true);
        jFileTxt.setText(myFile);
    }//GEN-LAST:event_jButton2ActionPerformed

    public String myPath(){
        return myFile;
    }
    
    private void jBtnFuzzyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFuzzyActionPerformed
        // TODO add your handling code here:
        
        //setting RELAX variable value
        int rv = 0;
        String relax = jRelaxTxt.getText();
        rv = Integer.valueOf(relax);
        String ideal = jIdealTxt.getText();
        int normal = 0;
        //System.out.println(rv);
        
            //read data using readExcel class
        readExcel exData = new readExcel();
        double[][] chartData = exData.readDataset(myFile);
        
                                //Line Chart with Series --used to show simulation data
//        DefaultCategoryDataset ds = new DefaultCategoryDataset();
//        final String series1 = "max";
//        final String series2 = "foodCount";
//        final String series3 = "min";
//        for(int i=0;i<chartData[0].length;i++){
//            ds.addValue(chartData[0][i], series1, String.valueOf(i));
//            ds.addValue(chartData[1][i], series2, String.valueOf(i));
//            ds.addValue((chartData[0][i]-rv), series3, String.valueOf(i));
//        }
//        JFreeChart simchart = ChartFactory.createLineChart("Simulation Result", "Day", "Value", ds, PlotOrientation.VERTICAL, true, true, false);
//        simchart.setBackgroundPaint(Color.white);
//        final CategoryPlot plot = (CategoryPlot) simchart.getPlot();
//        plot.setBackgroundPaint(Color.lightGray);
//        plot.setRangeGridlinePaint(Color.white);
//        ChartFrame fr = new ChartFrame("Simulation Result", simchart);
//        fr.setVisible(true);
//        fr.setSize(1000, 400);
        
                        //fuzzy result
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        double fx, Dx;
        
        String choice = jCBFuzzyType.getSelectedItem().toString();
        if(choice == "One Side"){
            for(int i=1;i<chartData[0].length;i++){
                Dx = chartData[0][i]-chartData[1][i];
                //Dx = chartData[1][i]-chartData[0][i];
                if(Dx>rv)
                    fx=0;
                else
                    fx=((rv+1)-Dx)/(rv+1);
                dataset.setValue(fx, "", String.valueOf(i));
            }
        }
        else{
            normal = Integer.valueOf(ideal);
            for(int i=1;i<chartData[0].length;i++){
                Dx = chartData[1][i]-normal;
                //Dx = chartData[1][i]-chartData[0][i];
                if(Dx>rv || Dx< -rv)
                    fx=0;
                else
                    fx=((rv+1)-abs(Dx))/(rv+1);
                System.out.println("Hasil simulasi:"+chartData[1][i]+" & Dx:"+Dx+" & fx:"+fx);
                dataset.setValue(fx, "", String.valueOf(i));
            }
        }
        
        JFreeChart chart = ChartFactory.createLineChart("Fuzzy Requirement Satisfaction", "Day", "Fuzzy Satisfaction", dataset, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.DARK_GRAY);
        ChartFrame frame = new ChartFrame("Fuzzy Representation",chart);
        frame.setVisible(true);
        frame.setSize(1000,400);

    }//GEN-LAST:event_jBtnFuzzyActionPerformed

    private void jSimulationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSimulationBtnActionPerformed
        // TODO add your handling code here:
        
        int rv = 0;
        String relax = jRelaxTxt.getText();
        rv = Integer.valueOf(relax);
        
        readExcel exData = new readExcel();
        double[][] chartData = exData.readDataset(myFile);
        
                                //Line Chart with Series --used to show simulation data
        DefaultCategoryDataset ds = new DefaultCategoryDataset();
        final String series1 = "max";
        final String series2 = "simulation";
        final String series3 = "min";
        int normal = 0;
        for(int i=0;i<chartData[0].length;i++){
            
            String choice = jCBFuzzyType.getSelectedItem().toString();
            if(choice == "One Side"){
                ds.addValue(chartData[0][i], series1, String.valueOf(i));
                ds.addValue(chartData[1][i], series2, String.valueOf(i));
                ds.addValue((chartData[0][i]-rv), series3, String.valueOf(i));
            }
            else{
                normal = Integer.valueOf(jIdealTxt.getText());
                //v = Integer.valueOf(jRelaxTxt.getText());
                ds.addValue(normal+rv, series1, String.valueOf(i));
                ds.addValue(chartData[1][i], series2, String.valueOf(i));
                ds.addValue(normal-rv, series3, String.valueOf(i));
            }
        }
        JFreeChart simchart = ChartFactory.createLineChart("Simulation Result", "Day", "Value", ds, PlotOrientation.VERTICAL, true, true, false);
        simchart.setBackgroundPaint(Color.white);
        final CategoryPlot plot = (CategoryPlot) simchart.getPlot();
        plot.setBackgroundPaint(Color.lightGray);
        plot.setRangeGridlinePaint(Color.white);
        ChartFrame fr = new ChartFrame("Simulation Result", simchart);
        fr.setVisible(true);
        fr.setSize(1000, 400);
    }//GEN-LAST:event_jSimulationBtnActionPerformed

    //private static final String FILE_NAME = "help.txt";
    private void jBtnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHelpActionPerformed
        // TODO add your handling code here:
    if (Desktop.isDesktopSupported()) {
        try {
            File myFile = new File("help.txt");
            Desktop.getDesktop().open(myFile);
        } catch (IOException ex) {
            // no application registered for PDFs
        }
    }
    }//GEN-LAST:event_jBtnHelpActionPerformed

    private void jCBFuzzyTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBFuzzyTypeActionPerformed
        // TODO add your handling code here:
        if(jCBFuzzyType.getSelectedItem()=="Two Side")
            jIdealTxt.setEnabled(true);
        else
            jIdealTxt.setEnabled(false);
    }//GEN-LAST:event_jCBFuzzyTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fuzzyChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fuzzyChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fuzzyChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fuzzyChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fuzzyChart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnFuzzy;
    private javax.swing.JButton jBtnHelp;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCBFuzzyType;
    private javax.swing.JTextField jFileTxt;
    private javax.swing.JTextField jIdealTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jRelaxTxt;
    private javax.swing.JButton jSimulationBtn;
    // End of variables declaration//GEN-END:variables
}
